// @generated by gen_backend_stubs.py from RegisterFunctionalization.cpp

#include <ATen/core/LegacyTypeDispatch.h>
#include <ATen/EmptyTensor.h>
#include <ATen/FunctionalTensorWrapper.h>
#include <ATen/MemoryOverlap.h>
#include <torch/library.h>

#include <ATen/Operators.h>
#include <ATen/NativeFunctions.h>
#include "torch_npu/csrc/aten/CustomFunctions.h"
#include "torch_npu/csrc/core/npu/NPUException.h"


namespace at_npu {
namespace functionalization {

// This keyset is used by functionalization when it calls into meta kernels
// to accurately propagate stride metadata.
// Exclude any modes: the purpose of calling into meta kernels is only as an implementation
// detail to perform shape inference, and we don't want any modal keys to run.
// Specifically, we want to prevent functionalization and Python modes from running.
constexpr auto exclude_keys_for_meta_dispatch =
    c10::functorch_transforms_ks |
    c10::DispatchKeySet({
        c10::DispatchKey::FuncTorchDynamicLayerBackMode,
        c10::DispatchKey::FuncTorchDynamicLayerFrontMode,
        c10::DispatchKey::Python
    });

// Helper around at::has_internal_overlap.
// The ATen util is used in hot-path eager mode: it's always fast,
// but might return TOO_HARD sometimes.
// During functionalization, we're ok taking a bit longer
// to detect memory overlap.
inline bool has_internal_overlap_helper(const at::Tensor t)
{
    auto has_overlap = at::has_internal_overlap(t);
    if (has_overlap == at::MemOverlap::Yes) {
        return true;
    }
    if (has_overlap == at::MemOverlap::No) {
        return false;
    }
    return false;
}


inline at::Tensor to_meta(const at::Tensor& t)
{
    if (!t.defined()) return t;
    return at::native::empty_strided_meta_symint(t.sym_sizes(), t.sym_strides(),
        c10::make_optional(t.scalar_type()) /* dtype */, c10::make_optional(t.layout() /* layout */),
        c10::make_optional(c10::Device(at::kMeta)) /* device */, c10::nullopt /* pin_memory */);
}

inline c10::optional<at::Tensor> to_meta(const c10::optional<at::Tensor>& t)
{
    if (t.has_value()) {
        return c10::make_optional<at::Tensor>(to_meta(*t));
    }
    return c10::nullopt;
}

inline std::vector<at::Tensor> to_meta(at::ITensorListRef t_list)
{
    std::vector<at::Tensor> outputs;
    outputs.reserve(t_list.size());
    for (const auto& tensor : t_list) {
        outputs.push_back(to_meta(tensor));
    }
    return outputs;
}

inline c10::List<at::Tensor> to_meta(const c10::List<at::Tensor>& t_list)
{
    c10::List<at::Tensor> outputs;
    outputs.reserve(t_list.size());
    for (const auto i : c10::irange(t_list.size())) {
        outputs.push_back(to_meta(t_list[i]));
    }
    return outputs;
}

inline c10::List<c10::optional<at::Tensor>> to_meta(const c10::List<c10::optional<at::Tensor>>& t_list)
{
    c10::List<c10::optional<at::Tensor>> outputs;
    outputs.reserve(t_list.size());
    for (const auto i : c10::irange(t_list.size())) {
        outputs.push_back(to_meta(t_list[i]));
    }
    return outputs;
}



at::Tensor & npu_format_cast__acl_format(c10::DispatchKeySet dispatchKeySet, at::Tensor & self, int64_t acl_format, ::std::optional<int64_t> customize_dtype) {
    if (true) {
        // Before converting the mutable op to its functional variant, run meta tensors through the original op.
        // This will help us catch shape errors that apply to inplace ops that wouldn't apply to their functional variants.
        // (We can only do this for inplace ops today though, because they technicaly all support meta tensors).
        auto self_meta = to_meta(self);
        at::AutoDispatchSkipFunctionalize func_guard;
        c10::impl::ExcludeDispatchKeyGuard guard(exclude_keys_for_meta_dispatch);
        at_npu::native::custom_ops::npu_format_cast_(self_meta, acl_format, customize_dtype);
    }

      at::Tensor self_;
      if (at::functionalization::impl::isFunctionalTensor(self)) {
        at::functionalization::impl::sync(self);
        self_ = at::functionalization::impl::from_functional_tensor(self);
      } else {
        self_ = self;
      }
    if (!(true && at::functionalization::impl::isFunctionalTensor(self))) {
        if (false) {
            // case 1: trying to mutate a non functional tensor with a functional tensor is an error
            TORCH_INTERNAL_ASSERT(false,
            "mutating a non-functional tensor with a functional tensor is not allowed.",
            " Please ensure that all of your inputs are wrapped inside of a functionalize() call.", PTA_ERROR(ErrCode::PARAM));
        } else {
            // case 2: arguments are not functional tensors, so we no-op and redispatch.
            at::AutoDispatchSkipFunctionalize guard;
            at::Tensor tmp_output = at_npu::native::custom_ops::npu_format_cast_(self_, acl_format, customize_dtype);
            return self;
        }
    } else {
        at::Tensor tmp_output;
        {
            at::AutoDispatchSkipFunctionalize guard;
            tmp_output = at_npu::native::custom_ops::npu_format_cast(self_, acl_format, customize_dtype);
        }
        at::functionalization::impl::replace_(self, tmp_output);
        at::functionalization::impl::commit_update(self);
        at::functionalization::impl::sync(self);
        return self;
    }
}

::std::tuple<at::Tensor,at::Tensor> npu_kv_rmsnorm_rope_cache_v2(c10::DispatchKeySet dispatchKeySet, const at::Tensor & kv, const at::Tensor & gamma, const at::Tensor & cos, const at::Tensor & sin, const at::Tensor & index, at::Tensor & k_cache, at::Tensor & ckv_cache, const ::std::optional<at::Tensor> & k_rope_scale, const ::std::optional<at::Tensor> & c_kv_scale, const ::std::optional<at::Tensor> & k_rope_offset, const ::std::optional<at::Tensor> & c_kv_offset, double epsilon, c10::string_view cache_mode, bool is_output_kv) {
    if (false) {
        // Before converting the mutable op to its functional variant, run meta tensors through the original op.
        // This will help us catch shape errors that apply to inplace ops that wouldn't apply to their functional variants.
        // (We can only do this for inplace ops today though, because they technicaly all support meta tensors).
        auto kv_meta = to_meta(kv);
        auto gamma_meta = to_meta(gamma);
        auto cos_meta = to_meta(cos);
        auto sin_meta = to_meta(sin);
        auto index_meta = to_meta(index);
        auto k_cache_meta = to_meta(k_cache);
        auto ckv_cache_meta = to_meta(ckv_cache);
        auto k_rope_scale_meta = to_meta(k_rope_scale);
        auto c_kv_scale_meta = to_meta(c_kv_scale);
        auto k_rope_offset_meta = to_meta(k_rope_offset);
        auto c_kv_offset_meta = to_meta(c_kv_offset);
        at::AutoDispatchSkipFunctionalize func_guard;
        c10::impl::ExcludeDispatchKeyGuard guard(exclude_keys_for_meta_dispatch);
        at_npu::native::custom_ops::npu_kv_rmsnorm_rope_cache_v2(kv_meta, gamma_meta, cos_meta, sin_meta, index_meta, k_cache_meta, ckv_cache_meta, k_rope_scale_meta, c_kv_scale_meta, k_rope_offset_meta, c_kv_offset_meta, epsilon, cache_mode, is_output_kv);
    }

      at::Tensor kv_;
      if (at::functionalization::impl::isFunctionalTensor(kv)) {
        at::functionalization::impl::sync(kv);
        kv_ = at::functionalization::impl::from_functional_tensor(kv);
      } else {
        kv_ = kv;
      }

      at::Tensor gamma_;
      if (at::functionalization::impl::isFunctionalTensor(gamma)) {
        at::functionalization::impl::sync(gamma);
        gamma_ = at::functionalization::impl::from_functional_tensor(gamma);
      } else {
        gamma_ = gamma;
      }

      at::Tensor cos_;
      if (at::functionalization::impl::isFunctionalTensor(cos)) {
        at::functionalization::impl::sync(cos);
        cos_ = at::functionalization::impl::from_functional_tensor(cos);
      } else {
        cos_ = cos;
      }

      at::Tensor sin_;
      if (at::functionalization::impl::isFunctionalTensor(sin)) {
        at::functionalization::impl::sync(sin);
        sin_ = at::functionalization::impl::from_functional_tensor(sin);
      } else {
        sin_ = sin;
      }

      at::Tensor index_;
      if (at::functionalization::impl::isFunctionalTensor(index)) {
        at::functionalization::impl::sync(index);
        index_ = at::functionalization::impl::from_functional_tensor(index);
      } else {
        index_ = index;
      }

      at::Tensor k_cache_;
      if (at::functionalization::impl::isFunctionalTensor(k_cache)) {
        at::functionalization::impl::sync(k_cache);
        k_cache_ = at::functionalization::impl::from_functional_tensor(k_cache);
      } else {
        k_cache_ = k_cache;
      }

      at::Tensor ckv_cache_;
      if (at::functionalization::impl::isFunctionalTensor(ckv_cache)) {
        at::functionalization::impl::sync(ckv_cache);
        ckv_cache_ = at::functionalization::impl::from_functional_tensor(ckv_cache);
      } else {
        ckv_cache_ = ckv_cache;
      }

      ::std::optional<at::Tensor> k_rope_scale_;
      if (at::functionalization::impl::isFunctionalTensor(k_rope_scale)) {
        at::functionalization::impl::sync(k_rope_scale);
        k_rope_scale_ = at::functionalization::impl::from_functional_tensor(k_rope_scale);
      } else {
        k_rope_scale_ = k_rope_scale;
      }

      ::std::optional<at::Tensor> c_kv_scale_;
      if (at::functionalization::impl::isFunctionalTensor(c_kv_scale)) {
        at::functionalization::impl::sync(c_kv_scale);
        c_kv_scale_ = at::functionalization::impl::from_functional_tensor(c_kv_scale);
      } else {
        c_kv_scale_ = c_kv_scale;
      }

      ::std::optional<at::Tensor> k_rope_offset_;
      if (at::functionalization::impl::isFunctionalTensor(k_rope_offset)) {
        at::functionalization::impl::sync(k_rope_offset);
        k_rope_offset_ = at::functionalization::impl::from_functional_tensor(k_rope_offset);
      } else {
        k_rope_offset_ = k_rope_offset;
      }

      ::std::optional<at::Tensor> c_kv_offset_;
      if (at::functionalization::impl::isFunctionalTensor(c_kv_offset)) {
        at::functionalization::impl::sync(c_kv_offset);
        c_kv_offset_ = at::functionalization::impl::from_functional_tensor(c_kv_offset);
      } else {
        c_kv_offset_ = c_kv_offset;
      }
    if (!(true && at::functionalization::impl::isFunctionalTensor(k_cache) && at::functionalization::impl::isFunctionalTensor(ckv_cache))) {
        if (false || at::functionalization::impl::isFunctionalTensor(kv) || at::functionalization::impl::isFunctionalTensor(gamma) || at::functionalization::impl::isFunctionalTensor(cos) || at::functionalization::impl::isFunctionalTensor(sin) || at::functionalization::impl::isFunctionalTensor(index) || at::functionalization::impl::isFunctionalTensor(k_rope_scale) || at::functionalization::impl::isFunctionalTensor(c_kv_scale) || at::functionalization::impl::isFunctionalTensor(k_rope_offset) || at::functionalization::impl::isFunctionalTensor(c_kv_offset)) {
            // case 1: trying to mutate a non functional tensor with a functional tensor is an error
            TORCH_INTERNAL_ASSERT(false,
            "mutating a non-functional tensor with a functional tensor is not allowed.",
            " Please ensure that all of your inputs are wrapped inside of a functionalize() call.", PTA_ERROR(ErrCode::PARAM));
        } else {
            // case 2: arguments are not functional tensors, so we no-op and redispatch.
            at::AutoDispatchSkipFunctionalize guard;
            ::std::tuple<at::Tensor,at::Tensor> tmp_output = at_npu::native::custom_ops::npu_kv_rmsnorm_rope_cache_v2(kv_, gamma_, cos_, sin_, index_, k_cache_, ckv_cache_, k_rope_scale_, c_kv_scale_, k_rope_offset_, c_kv_offset_, epsilon, cache_mode, is_output_kv);
            return ::std::tuple<at::Tensor,at::Tensor>(std::get<0>(tmp_output), std::get<1>(tmp_output));
        }
    } else {
        ::std::tuple<at::Tensor,at::Tensor,at::Tensor,at::Tensor> tmp_output;
        {
            at::AutoDispatchSkipFunctionalize guard;
            tmp_output = at_npu::native::custom_ops::npu_kv_rmsnorm_rope_cache_v2_functional(kv_, gamma_, cos_, sin_, index_, k_cache_, ckv_cache_, k_rope_scale_, c_kv_scale_, k_rope_offset_, c_kv_offset_, epsilon, cache_mode, is_output_kv);
        }
          auto output_0 = at::functionalization::impl::to_functional_tensor(std::get<0>(tmp_output));
  auto output_1 = at::functionalization::impl::to_functional_tensor(std::get<1>(tmp_output));
at::functionalization::impl::replace_(k_cache, std::get<2>(tmp_output));
        at::functionalization::impl::commit_update(k_cache);
        at::functionalization::impl::sync(k_cache);
at::functionalization::impl::replace_(ckv_cache, std::get<3>(tmp_output));
        at::functionalization::impl::commit_update(ckv_cache);
        at::functionalization::impl::sync(ckv_cache);
        return ::std::tuple<at::Tensor,at::Tensor>(output_0, output_1);
    }
}

at::Tensor & npu_batch_gather_matmul_(c10::DispatchKeySet dispatchKeySet, at::Tensor & self, const at::Tensor & x, const at::Tensor & weight_b, const at::Tensor & indices, const ::std::optional<at::Tensor> & weight_a, int64_t layer_idx, double scale, int64_t y_offset, int64_t y_slice_size) {
    if (true) {
        // Before converting the mutable op to its functional variant, run meta tensors through the original op.
        // This will help us catch shape errors that apply to inplace ops that wouldn't apply to their functional variants.
        // (We can only do this for inplace ops today though, because they technicaly all support meta tensors).
        auto self_meta = to_meta(self);
        auto x_meta = to_meta(x);
        auto weight_b_meta = to_meta(weight_b);
        auto indices_meta = to_meta(indices);
        auto weight_a_meta = to_meta(weight_a);
        at::AutoDispatchSkipFunctionalize func_guard;
        c10::impl::ExcludeDispatchKeyGuard guard(exclude_keys_for_meta_dispatch);
        at_npu::native::custom_ops::npu_batch_gather_matmul_(self_meta, x_meta, weight_b_meta, indices_meta, weight_a_meta, layer_idx, scale, y_offset, y_slice_size);
    }

      at::Tensor self_;
      if (at::functionalization::impl::isFunctionalTensor(self)) {
        at::functionalization::impl::sync(self);
        self_ = at::functionalization::impl::from_functional_tensor(self);
      } else {
        self_ = self;
      }

      at::Tensor x_;
      if (at::functionalization::impl::isFunctionalTensor(x)) {
        at::functionalization::impl::sync(x);
        x_ = at::functionalization::impl::from_functional_tensor(x);
      } else {
        x_ = x;
      }

      at::Tensor weight_b_;
      if (at::functionalization::impl::isFunctionalTensor(weight_b)) {
        at::functionalization::impl::sync(weight_b);
        weight_b_ = at::functionalization::impl::from_functional_tensor(weight_b);
      } else {
        weight_b_ = weight_b;
      }

      at::Tensor indices_;
      if (at::functionalization::impl::isFunctionalTensor(indices)) {
        at::functionalization::impl::sync(indices);
        indices_ = at::functionalization::impl::from_functional_tensor(indices);
      } else {
        indices_ = indices;
      }

      ::std::optional<at::Tensor> weight_a_;
      if (at::functionalization::impl::isFunctionalTensor(weight_a)) {
        at::functionalization::impl::sync(weight_a);
        weight_a_ = at::functionalization::impl::from_functional_tensor(weight_a);
      } else {
        weight_a_ = weight_a;
      }
    if (!(true && at::functionalization::impl::isFunctionalTensor(self))) {
        if (false || at::functionalization::impl::isFunctionalTensor(x) || at::functionalization::impl::isFunctionalTensor(weight_b) || at::functionalization::impl::isFunctionalTensor(indices) || at::functionalization::impl::isFunctionalTensor(weight_a)) {
            // case 1: trying to mutate a non functional tensor with a functional tensor is an error
            TORCH_INTERNAL_ASSERT(false,
            "mutating a non-functional tensor with a functional tensor is not allowed.",
            " Please ensure that all of your inputs are wrapped inside of a functionalize() call.", PTA_ERROR(ErrCode::PARAM));
        } else {
            // case 2: arguments are not functional tensors, so we no-op and redispatch.
            at::AutoDispatchSkipFunctionalize guard;
            at::Tensor tmp_output = at_npu::native::custom_ops::npu_batch_gather_matmul_(self_, x_, weight_b_, indices_, weight_a_, layer_idx, scale, y_offset, y_slice_size);
            return self;
        }
    } else {
        at::Tensor tmp_output;
        {
            at::AutoDispatchSkipFunctionalize guard;
            tmp_output = at_npu::native::custom_ops::npu_batch_gather_matmul(self_, x_, weight_b_, indices_, weight_a_, layer_idx, scale, y_offset, y_slice_size);
        }
        at::functionalization::impl::replace_(self, tmp_output);
        at::functionalization::impl::commit_update(self);
        at::functionalization::impl::sync(self);
        return self;
    }
}

at::Tensor & npu_broadcast_out_out(c10::DispatchKeySet dispatchKeySet, const at::Tensor & self, at::IntArrayRef size, at::Tensor & out) {
    if (false) {
        // Before converting the mutable op to its functional variant, run meta tensors through the original op.
        // This will help us catch shape errors that apply to inplace ops that wouldn't apply to their functional variants.
        // (We can only do this for inplace ops today though, because they technicaly all support meta tensors).
        auto self_meta = to_meta(self);
        auto out_meta = to_meta(out);
        at::AutoDispatchSkipFunctionalize func_guard;
        c10::impl::ExcludeDispatchKeyGuard guard(exclude_keys_for_meta_dispatch);
        at_npu::native::custom_ops::npu_broadcast_out(self_meta, size, out_meta);
    }

      at::Tensor self_;
      if (at::functionalization::impl::isFunctionalTensor(self)) {
        at::functionalization::impl::sync(self);
        self_ = at::functionalization::impl::from_functional_tensor(self);
      } else {
        self_ = self;
      }

      at::Tensor out_;
      if (at::functionalization::impl::isFunctionalTensor(out)) {
        at::functionalization::impl::sync(out);
        out_ = at::functionalization::impl::from_functional_tensor(out);
      } else {
        out_ = out;
      }
    if (!(true && at::functionalization::impl::isFunctionalTensor(out))) {
        if (false || at::functionalization::impl::isFunctionalTensor(self)) {
            // case 1: trying to mutate a non functional tensor with a functional tensor is an error
            TORCH_INTERNAL_ASSERT(false,
            "mutating a non-functional tensor with a functional tensor is not allowed.",
            " Please ensure that all of your inputs are wrapped inside of a functionalize() call.", PTA_ERROR(ErrCode::PARAM));
        } else {
            // case 2: arguments are not functional tensors, so we no-op and redispatch.
            at::AutoDispatchSkipFunctionalize guard;
            at::Tensor tmp_output = at_npu::native::custom_ops::npu_broadcast_out(self_, size, out_);
            return out;
        }
    } else {
        at::Tensor tmp_output;
        {
            at::AutoDispatchSkipFunctionalize guard;
            tmp_output = at_npu::native::custom_ops::npu_broadcast(self_, size);
        }
        at::functionalization::impl::replace_(out, tmp_output);
        at::functionalization::impl::commit_update(out);
        at::functionalization::impl::sync(out);
        return out;
    }
}

at::Tensor & npu_conv2d_out_out(c10::DispatchKeySet dispatchKeySet, const at::Tensor & input, const at::Tensor & weight, const ::std::optional<at::Tensor> & bias, at::IntArrayRef stride, at::IntArrayRef padding, at::IntArrayRef dilation, int64_t groups, at::Tensor & out) {
    if (false) {
        // Before converting the mutable op to its functional variant, run meta tensors through the original op.
        // This will help us catch shape errors that apply to inplace ops that wouldn't apply to their functional variants.
        // (We can only do this for inplace ops today though, because they technicaly all support meta tensors).
        auto input_meta = to_meta(input);
        auto weight_meta = to_meta(weight);
        auto bias_meta = to_meta(bias);
        auto out_meta = to_meta(out);
        at::AutoDispatchSkipFunctionalize func_guard;
        c10::impl::ExcludeDispatchKeyGuard guard(exclude_keys_for_meta_dispatch);
        at_npu::native::custom_ops::npu_conv2d_out(input_meta, weight_meta, bias_meta, stride, padding, dilation, groups, out_meta);
    }

      at::Tensor input_;
      if (at::functionalization::impl::isFunctionalTensor(input)) {
        at::functionalization::impl::sync(input);
        input_ = at::functionalization::impl::from_functional_tensor(input);
      } else {
        input_ = input;
      }

      at::Tensor weight_;
      if (at::functionalization::impl::isFunctionalTensor(weight)) {
        at::functionalization::impl::sync(weight);
        weight_ = at::functionalization::impl::from_functional_tensor(weight);
      } else {
        weight_ = weight;
      }

      ::std::optional<at::Tensor> bias_;
      if (at::functionalization::impl::isFunctionalTensor(bias)) {
        at::functionalization::impl::sync(bias);
        bias_ = at::functionalization::impl::from_functional_tensor(bias);
      } else {
        bias_ = bias;
      }

      at::Tensor out_;
      if (at::functionalization::impl::isFunctionalTensor(out)) {
        at::functionalization::impl::sync(out);
        out_ = at::functionalization::impl::from_functional_tensor(out);
      } else {
        out_ = out;
      }
    if (!(true && at::functionalization::impl::isFunctionalTensor(out))) {
        if (false || at::functionalization::impl::isFunctionalTensor(input) || at::functionalization::impl::isFunctionalTensor(weight) || at::functionalization::impl::isFunctionalTensor(bias)) {
            // case 1: trying to mutate a non functional tensor with a functional tensor is an error
            TORCH_INTERNAL_ASSERT(false,
            "mutating a non-functional tensor with a functional tensor is not allowed.",
            " Please ensure that all of your inputs are wrapped inside of a functionalize() call.", PTA_ERROR(ErrCode::PARAM));
        } else {
            // case 2: arguments are not functional tensors, so we no-op and redispatch.
            at::AutoDispatchSkipFunctionalize guard;
            at::Tensor tmp_output = at_npu::native::custom_ops::npu_conv2d_out(input_, weight_, bias_, stride, padding, dilation, groups, out_);
            return out;
        }
    } else {
        at::Tensor tmp_output;
        {
            at::AutoDispatchSkipFunctionalize guard;
            tmp_output = at_npu::native::custom_ops::npu_conv2d(input_, weight_, bias_, stride, padding, dilation, groups);
        }
        at::functionalization::impl::replace_(out, tmp_output);
        at::functionalization::impl::commit_update(out);
        at::functionalization::impl::sync(out);
        return out;
    }
}

at::Tensor & npu_conv3d_out_out(c10::DispatchKeySet dispatchKeySet, const at::Tensor & input, const at::Tensor & weight, const ::std::optional<at::Tensor> & bias, at::IntArrayRef stride, at::IntArrayRef padding, at::IntArrayRef dilation, int64_t groups, at::Tensor & out) {
    if (false) {
        // Before converting the mutable op to its functional variant, run meta tensors through the original op.
        // This will help us catch shape errors that apply to inplace ops that wouldn't apply to their functional variants.
        // (We can only do this for inplace ops today though, because they technicaly all support meta tensors).
        auto input_meta = to_meta(input);
        auto weight_meta = to_meta(weight);
        auto bias_meta = to_meta(bias);
        auto out_meta = to_meta(out);
        at::AutoDispatchSkipFunctionalize func_guard;
        c10::impl::ExcludeDispatchKeyGuard guard(exclude_keys_for_meta_dispatch);
        at_npu::native::custom_ops::npu_conv3d_out(input_meta, weight_meta, bias_meta, stride, padding, dilation, groups, out_meta);
    }

      at::Tensor input_;
      if (at::functionalization::impl::isFunctionalTensor(input)) {
        at::functionalization::impl::sync(input);
        input_ = at::functionalization::impl::from_functional_tensor(input);
      } else {
        input_ = input;
      }

      at::Tensor weight_;
      if (at::functionalization::impl::isFunctionalTensor(weight)) {
        at::functionalization::impl::sync(weight);
        weight_ = at::functionalization::impl::from_functional_tensor(weight);
      } else {
        weight_ = weight;
      }

      ::std::optional<at::Tensor> bias_;
      if (at::functionalization::impl::isFunctionalTensor(bias)) {
        at::functionalization::impl::sync(bias);
        bias_ = at::functionalization::impl::from_functional_tensor(bias);
      } else {
        bias_ = bias;
      }

      at::Tensor out_;
      if (at::functionalization::impl::isFunctionalTensor(out)) {
        at::functionalization::impl::sync(out);
        out_ = at::functionalization::impl::from_functional_tensor(out);
      } else {
        out_ = out;
      }
    if (!(true && at::functionalization::impl::isFunctionalTensor(out))) {
        if (false || at::functionalization::impl::isFunctionalTensor(input) || at::functionalization::impl::isFunctionalTensor(weight) || at::functionalization::impl::isFunctionalTensor(bias)) {
            // case 1: trying to mutate a non functional tensor with a functional tensor is an error
            TORCH_INTERNAL_ASSERT(false,
            "mutating a non-functional tensor with a functional tensor is not allowed.",
            " Please ensure that all of your inputs are wrapped inside of a functionalize() call.", PTA_ERROR(ErrCode::PARAM));
        } else {
            // case 2: arguments are not functional tensors, so we no-op and redispatch.
            at::AutoDispatchSkipFunctionalize guard;
            at::Tensor tmp_output = at_npu::native::custom_ops::npu_conv3d_out(input_, weight_, bias_, stride, padding, dilation, groups, out_);
            return out;
        }
    } else {
        at::Tensor tmp_output;
        {
            at::AutoDispatchSkipFunctionalize guard;
            tmp_output = at_npu::native::custom_ops::npu_conv3d(input_, weight_, bias_, stride, padding, dilation, groups);
        }
        at::functionalization::impl::replace_(out, tmp_output);
        at::functionalization::impl::commit_update(out);
        at::functionalization::impl::sync(out);
        return out;
    }
}

at::Tensor & npu_indexing_out_out(c10::DispatchKeySet dispatchKeySet, const at::Tensor & self, at::IntArrayRef begin, at::IntArrayRef end, at::IntArrayRef strides, int64_t begin_mask, int64_t end_mask, int64_t ellipsis_mask, int64_t new_axis_mask, int64_t shrink_axis_mask, at::Tensor & out) {
    if (false) {
        // Before converting the mutable op to its functional variant, run meta tensors through the original op.
        // This will help us catch shape errors that apply to inplace ops that wouldn't apply to their functional variants.
        // (We can only do this for inplace ops today though, because they technicaly all support meta tensors).
        auto self_meta = to_meta(self);
        auto out_meta = to_meta(out);
        at::AutoDispatchSkipFunctionalize func_guard;
        c10::impl::ExcludeDispatchKeyGuard guard(exclude_keys_for_meta_dispatch);
        at_npu::native::custom_ops::npu_indexing_out(self_meta, begin, end, strides, begin_mask, end_mask, ellipsis_mask, new_axis_mask, shrink_axis_mask, out_meta);
    }

      at::Tensor self_;
      if (at::functionalization::impl::isFunctionalTensor(self)) {
        at::functionalization::impl::sync(self);
        self_ = at::functionalization::impl::from_functional_tensor(self);
      } else {
        self_ = self;
      }

      at::Tensor out_;
      if (at::functionalization::impl::isFunctionalTensor(out)) {
        at::functionalization::impl::sync(out);
        out_ = at::functionalization::impl::from_functional_tensor(out);
      } else {
        out_ = out;
      }
    if (!(true && at::functionalization::impl::isFunctionalTensor(out))) {
        if (false || at::functionalization::impl::isFunctionalTensor(self)) {
            // case 1: trying to mutate a non functional tensor with a functional tensor is an error
            TORCH_INTERNAL_ASSERT(false,
            "mutating a non-functional tensor with a functional tensor is not allowed.",
            " Please ensure that all of your inputs are wrapped inside of a functionalize() call.", PTA_ERROR(ErrCode::PARAM));
        } else {
            // case 2: arguments are not functional tensors, so we no-op and redispatch.
            at::AutoDispatchSkipFunctionalize guard;
            at::Tensor tmp_output = at_npu::native::custom_ops::npu_indexing_out(self_, begin, end, strides, begin_mask, end_mask, ellipsis_mask, new_axis_mask, shrink_axis_mask, out_);
            return out;
        }
    } else {
        at::Tensor tmp_output;
        {
            at::AutoDispatchSkipFunctionalize guard;
            tmp_output = at_npu::native::custom_ops::npu_indexing(self_, begin, end, strides, begin_mask, end_mask, ellipsis_mask, new_axis_mask, shrink_axis_mask);
        }
        at::functionalization::impl::replace_(out, tmp_output);
        at::functionalization::impl::commit_update(out);
        at::functionalization::impl::sync(out);
        return out;
    }
}

at::Tensor & npu_quant_scatter_(c10::DispatchKeySet dispatchKeySet, at::Tensor & self, const at::Tensor & indices, const at::Tensor & updates, const at::Tensor & quant_scales, const ::std::optional<at::Tensor> & quant_zero_points, int64_t axis, int64_t quant_axis, c10::string_view reduce) {
    if (true) {
        // Before converting the mutable op to its functional variant, run meta tensors through the original op.
        // This will help us catch shape errors that apply to inplace ops that wouldn't apply to their functional variants.
        // (We can only do this for inplace ops today though, because they technicaly all support meta tensors).
        auto self_meta = to_meta(self);
        auto indices_meta = to_meta(indices);
        auto updates_meta = to_meta(updates);
        auto quant_scales_meta = to_meta(quant_scales);
        auto quant_zero_points_meta = to_meta(quant_zero_points);
        at::AutoDispatchSkipFunctionalize func_guard;
        c10::impl::ExcludeDispatchKeyGuard guard(exclude_keys_for_meta_dispatch);
        at_npu::native::custom_ops::npu_quant_scatter_(self_meta, indices_meta, updates_meta, quant_scales_meta, quant_zero_points_meta, axis, quant_axis, reduce);
    }

      at::Tensor self_;
      if (at::functionalization::impl::isFunctionalTensor(self)) {
        at::functionalization::impl::sync(self);
        self_ = at::functionalization::impl::from_functional_tensor(self);
      } else {
        self_ = self;
      }

      at::Tensor indices_;
      if (at::functionalization::impl::isFunctionalTensor(indices)) {
        at::functionalization::impl::sync(indices);
        indices_ = at::functionalization::impl::from_functional_tensor(indices);
      } else {
        indices_ = indices;
      }

      at::Tensor updates_;
      if (at::functionalization::impl::isFunctionalTensor(updates)) {
        at::functionalization::impl::sync(updates);
        updates_ = at::functionalization::impl::from_functional_tensor(updates);
      } else {
        updates_ = updates;
      }

      at::Tensor quant_scales_;
      if (at::functionalization::impl::isFunctionalTensor(quant_scales)) {
        at::functionalization::impl::sync(quant_scales);
        quant_scales_ = at::functionalization::impl::from_functional_tensor(quant_scales);
      } else {
        quant_scales_ = quant_scales;
      }

      ::std::optional<at::Tensor> quant_zero_points_;
      if (at::functionalization::impl::isFunctionalTensor(quant_zero_points)) {
        at::functionalization::impl::sync(quant_zero_points);
        quant_zero_points_ = at::functionalization::impl::from_functional_tensor(quant_zero_points);
      } else {
        quant_zero_points_ = quant_zero_points;
      }
    if (!(true && at::functionalization::impl::isFunctionalTensor(self))) {
        if (false || at::functionalization::impl::isFunctionalTensor(indices) || at::functionalization::impl::isFunctionalTensor(updates) || at::functionalization::impl::isFunctionalTensor(quant_scales) || at::functionalization::impl::isFunctionalTensor(quant_zero_points)) {
            // case 1: trying to mutate a non functional tensor with a functional tensor is an error
            TORCH_INTERNAL_ASSERT(false,
            "mutating a non-functional tensor with a functional tensor is not allowed.",
            " Please ensure that all of your inputs are wrapped inside of a functionalize() call.", PTA_ERROR(ErrCode::PARAM));
        } else {
            // case 2: arguments are not functional tensors, so we no-op and redispatch.
            at::AutoDispatchSkipFunctionalize guard;
            at::Tensor tmp_output = at_npu::native::custom_ops::npu_quant_scatter_(self_, indices_, updates_, quant_scales_, quant_zero_points_, axis, quant_axis, reduce);
            return self;
        }
    } else {
        at::Tensor tmp_output;
        {
            at::AutoDispatchSkipFunctionalize guard;
            tmp_output = at_npu::native::custom_ops::npu_quant_scatter(self_, indices_, updates_, quant_scales_, quant_zero_points_, axis, quant_axis, reduce);
        }
        at::functionalization::impl::replace_(self, tmp_output);
        at::functionalization::impl::commit_update(self);
        at::functionalization::impl::sync(self);
        return self;
    }
}

at::Tensor & npu_reshape_out_out(c10::DispatchKeySet dispatchKeySet, const at::Tensor & self, at::IntArrayRef shape, bool can_refresh, at::Tensor & out) {
    if (false) {
        // Before converting the mutable op to its functional variant, run meta tensors through the original op.
        // This will help us catch shape errors that apply to inplace ops that wouldn't apply to their functional variants.
        // (We can only do this for inplace ops today though, because they technicaly all support meta tensors).
        auto self_meta = to_meta(self);
        auto out_meta = to_meta(out);
        at::AutoDispatchSkipFunctionalize func_guard;
        c10::impl::ExcludeDispatchKeyGuard guard(exclude_keys_for_meta_dispatch);
        at_npu::native::custom_ops::npu_reshape_out(self_meta, shape, can_refresh, out_meta);
    }

      at::Tensor self_;
      if (at::functionalization::impl::isFunctionalTensor(self)) {
        at::functionalization::impl::sync(self);
        self_ = at::functionalization::impl::from_functional_tensor(self);
      } else {
        self_ = self;
      }

      at::Tensor out_;
      if (at::functionalization::impl::isFunctionalTensor(out)) {
        at::functionalization::impl::sync(out);
        out_ = at::functionalization::impl::from_functional_tensor(out);
      } else {
        out_ = out;
      }
    if (!(true && at::functionalization::impl::isFunctionalTensor(out))) {
        if (false || at::functionalization::impl::isFunctionalTensor(self)) {
            // case 1: trying to mutate a non functional tensor with a functional tensor is an error
            TORCH_INTERNAL_ASSERT(false,
            "mutating a non-functional tensor with a functional tensor is not allowed.",
            " Please ensure that all of your inputs are wrapped inside of a functionalize() call.", PTA_ERROR(ErrCode::PARAM));
        } else {
            // case 2: arguments are not functional tensors, so we no-op and redispatch.
            at::AutoDispatchSkipFunctionalize guard;
            at::Tensor tmp_output = at_npu::native::custom_ops::npu_reshape_out(self_, shape, can_refresh, out_);
            return out;
        }
    } else {
        at::Tensor tmp_output;
        {
            at::AutoDispatchSkipFunctionalize guard;
            tmp_output = at_npu::native::custom_ops::npu_reshape(self_, shape, can_refresh);
        }
        at::functionalization::impl::replace_(out, tmp_output);
        at::functionalization::impl::commit_update(out);
        at::functionalization::impl::sync(out);
        return out;
    }
}

void npu_scatter_list_(c10::DispatchKeySet dispatchKeySet, at::TensorList self, const at::Tensor & indices, const at::Tensor & updates, const ::std::optional<at::Tensor> & mask, c10::string_view reduce, int64_t axis) {
    if (true) {
        // Before converting the mutable op to its functional variant, run meta tensors through the original op.
        // This will help us catch shape errors that apply to inplace ops that wouldn't apply to their functional variants.
        // (We can only do this for inplace ops today though, because they technicaly all support meta tensors).
        auto self_meta = to_meta(self);
        auto indices_meta = to_meta(indices);
        auto updates_meta = to_meta(updates);
        auto mask_meta = to_meta(mask);
        at::AutoDispatchSkipFunctionalize func_guard;
        c10::impl::ExcludeDispatchKeyGuard guard(exclude_keys_for_meta_dispatch);
        at_npu::native::custom_ops::npu_scatter_list_(self_meta, indices_meta, updates_meta, mask_meta, reduce, axis);
    }

      ::std::vector<at::Tensor> self_;
      if (at::functionalization::impl::isFunctionalTensor(self)) {
        at::functionalization::impl::sync(self);
        self_ = at::functionalization::impl::from_functional_tensor(self);
      } else {
        self_ = self.vec();
      }

      at::Tensor indices_;
      if (at::functionalization::impl::isFunctionalTensor(indices)) {
        at::functionalization::impl::sync(indices);
        indices_ = at::functionalization::impl::from_functional_tensor(indices);
      } else {
        indices_ = indices;
      }

      at::Tensor updates_;
      if (at::functionalization::impl::isFunctionalTensor(updates)) {
        at::functionalization::impl::sync(updates);
        updates_ = at::functionalization::impl::from_functional_tensor(updates);
      } else {
        updates_ = updates;
      }

      ::std::optional<at::Tensor> mask_;
      if (at::functionalization::impl::isFunctionalTensor(mask)) {
        at::functionalization::impl::sync(mask);
        mask_ = at::functionalization::impl::from_functional_tensor(mask);
      } else {
        mask_ = mask;
      }
    if (!(true && at::functionalization::impl::isFunctionalTensor(self))) {
        if (false || at::functionalization::impl::isFunctionalTensor(indices) || at::functionalization::impl::isFunctionalTensor(updates) || at::functionalization::impl::isFunctionalTensor(mask)) {
            // case 1: trying to mutate a non functional tensor with a functional tensor is an error
            TORCH_INTERNAL_ASSERT(false,
            "mutating a non-functional tensor with a functional tensor is not allowed.",
            " Please ensure that all of your inputs are wrapped inside of a functionalize() call.", PTA_ERROR(ErrCode::PARAM));
        } else {
            // case 2: arguments are not functional tensors, so we no-op and redispatch.
            at::AutoDispatchSkipFunctionalize guard;
            at_npu::native::custom_ops::npu_scatter_list_(self_, indices_, updates_, mask_, reduce, axis);

        }
    } else {
        ::std::vector<at::Tensor> tmp_output;
        {
            at::AutoDispatchSkipFunctionalize guard;
            tmp_output = at_npu::native::custom_ops::npu_scatter_list(self_, indices_, updates_, mask_, reduce, axis);
        }
        at::functionalization::impl::replace_(self, tmp_output);
        at::functionalization::impl::commit_update(self);
        at::functionalization::impl::sync(self);

    }
}

at::Tensor & npu_scatter_nd_update_(c10::DispatchKeySet dispatchKeySet, at::Tensor & self, const at::Tensor & indices, const at::Tensor & updates) {
    if (true) {
        // Before converting the mutable op to its functional variant, run meta tensors through the original op.
        // This will help us catch shape errors that apply to inplace ops that wouldn't apply to their functional variants.
        // (We can only do this for inplace ops today though, because they technicaly all support meta tensors).
        auto self_meta = to_meta(self);
        auto indices_meta = to_meta(indices);
        auto updates_meta = to_meta(updates);
        at::AutoDispatchSkipFunctionalize func_guard;
        c10::impl::ExcludeDispatchKeyGuard guard(exclude_keys_for_meta_dispatch);
        at_npu::native::custom_ops::npu_scatter_nd_update_(self_meta, indices_meta, updates_meta);
    }

      at::Tensor self_;
      if (at::functionalization::impl::isFunctionalTensor(self)) {
        at::functionalization::impl::sync(self);
        self_ = at::functionalization::impl::from_functional_tensor(self);
      } else {
        self_ = self;
      }

      at::Tensor indices_;
      if (at::functionalization::impl::isFunctionalTensor(indices)) {
        at::functionalization::impl::sync(indices);
        indices_ = at::functionalization::impl::from_functional_tensor(indices);
      } else {
        indices_ = indices;
      }

      at::Tensor updates_;
      if (at::functionalization::impl::isFunctionalTensor(updates)) {
        at::functionalization::impl::sync(updates);
        updates_ = at::functionalization::impl::from_functional_tensor(updates);
      } else {
        updates_ = updates;
      }
    if (!(true && at::functionalization::impl::isFunctionalTensor(self))) {
        if (false || at::functionalization::impl::isFunctionalTensor(indices) || at::functionalization::impl::isFunctionalTensor(updates)) {
            // case 1: trying to mutate a non functional tensor with a functional tensor is an error
            TORCH_INTERNAL_ASSERT(false,
            "mutating a non-functional tensor with a functional tensor is not allowed.",
            " Please ensure that all of your inputs are wrapped inside of a functionalize() call.", PTA_ERROR(ErrCode::PARAM));
        } else {
            // case 2: arguments are not functional tensors, so we no-op and redispatch.
            at::AutoDispatchSkipFunctionalize guard;
            at::Tensor tmp_output = at_npu::native::custom_ops::npu_scatter_nd_update_(self_, indices_, updates_);
            return self;
        }
    } else {
        at::Tensor tmp_output;
        {
            at::AutoDispatchSkipFunctionalize guard;
            tmp_output = at_npu::native::custom_ops::npu_scatter_nd_update(self_, indices_, updates_);
        }
        at::functionalization::impl::replace_(self, tmp_output);
        at::functionalization::impl::commit_update(self);
        at::functionalization::impl::sync(self);
        return self;
    }
}

void npu_scatter_pa_kv_cache(c10::DispatchKeySet dispatchKeySet, const at::Tensor & key, const at::Tensor & value, at::Tensor & key_cache, at::Tensor & value_cache, const at::Tensor & slot_mapping, const ::std::optional<at::Tensor> & compress_lens, const ::std::optional<at::Tensor> & compress_seq_offsets, const ::std::optional<at::Tensor> & seq_lens) {
    if (false) {
        // Before converting the mutable op to its functional variant, run meta tensors through the original op.
        // This will help us catch shape errors that apply to inplace ops that wouldn't apply to their functional variants.
        // (We can only do this for inplace ops today though, because they technicaly all support meta tensors).
        auto key_meta = to_meta(key);
        auto value_meta = to_meta(value);
        auto key_cache_meta = to_meta(key_cache);
        auto value_cache_meta = to_meta(value_cache);
        auto slot_mapping_meta = to_meta(slot_mapping);
        auto compress_lens_meta = to_meta(compress_lens);
        auto compress_seq_offsets_meta = to_meta(compress_seq_offsets);
        auto seq_lens_meta = to_meta(seq_lens);
        at::AutoDispatchSkipFunctionalize func_guard;
        c10::impl::ExcludeDispatchKeyGuard guard(exclude_keys_for_meta_dispatch);
        at_npu::native::custom_ops::npu_scatter_pa_kv_cache(key_meta, value_meta, key_cache_meta, value_cache_meta, slot_mapping_meta, compress_lens_meta, compress_seq_offsets_meta, seq_lens_meta);
    }

      at::Tensor key_;
      if (at::functionalization::impl::isFunctionalTensor(key)) {
        at::functionalization::impl::sync(key);
        key_ = at::functionalization::impl::from_functional_tensor(key);
      } else {
        key_ = key;
      }

      at::Tensor value_;
      if (at::functionalization::impl::isFunctionalTensor(value)) {
        at::functionalization::impl::sync(value);
        value_ = at::functionalization::impl::from_functional_tensor(value);
      } else {
        value_ = value;
      }

      at::Tensor key_cache_;
      if (at::functionalization::impl::isFunctionalTensor(key_cache)) {
        at::functionalization::impl::sync(key_cache);
        key_cache_ = at::functionalization::impl::from_functional_tensor(key_cache);
      } else {
        key_cache_ = key_cache;
      }

      at::Tensor value_cache_;
      if (at::functionalization::impl::isFunctionalTensor(value_cache)) {
        at::functionalization::impl::sync(value_cache);
        value_cache_ = at::functionalization::impl::from_functional_tensor(value_cache);
      } else {
        value_cache_ = value_cache;
      }

      at::Tensor slot_mapping_;
      if (at::functionalization::impl::isFunctionalTensor(slot_mapping)) {
        at::functionalization::impl::sync(slot_mapping);
        slot_mapping_ = at::functionalization::impl::from_functional_tensor(slot_mapping);
      } else {
        slot_mapping_ = slot_mapping;
      }

      ::std::optional<at::Tensor> compress_lens_;
      if (at::functionalization::impl::isFunctionalTensor(compress_lens)) {
        at::functionalization::impl::sync(compress_lens);
        compress_lens_ = at::functionalization::impl::from_functional_tensor(compress_lens);
      } else {
        compress_lens_ = compress_lens;
      }

      ::std::optional<at::Tensor> compress_seq_offsets_;
      if (at::functionalization::impl::isFunctionalTensor(compress_seq_offsets)) {
        at::functionalization::impl::sync(compress_seq_offsets);
        compress_seq_offsets_ = at::functionalization::impl::from_functional_tensor(compress_seq_offsets);
      } else {
        compress_seq_offsets_ = compress_seq_offsets;
      }

      ::std::optional<at::Tensor> seq_lens_;
      if (at::functionalization::impl::isFunctionalTensor(seq_lens)) {
        at::functionalization::impl::sync(seq_lens);
        seq_lens_ = at::functionalization::impl::from_functional_tensor(seq_lens);
      } else {
        seq_lens_ = seq_lens;
      }
    if (!(true && at::functionalization::impl::isFunctionalTensor(key_cache) && at::functionalization::impl::isFunctionalTensor(value_cache))) {
        if (false || at::functionalization::impl::isFunctionalTensor(key) || at::functionalization::impl::isFunctionalTensor(value) || at::functionalization::impl::isFunctionalTensor(slot_mapping) || at::functionalization::impl::isFunctionalTensor(compress_lens) || at::functionalization::impl::isFunctionalTensor(compress_seq_offsets) || at::functionalization::impl::isFunctionalTensor(seq_lens)) {
            // case 1: trying to mutate a non functional tensor with a functional tensor is an error
            TORCH_INTERNAL_ASSERT(false,
            "mutating a non-functional tensor with a functional tensor is not allowed.",
            " Please ensure that all of your inputs are wrapped inside of a functionalize() call.", PTA_ERROR(ErrCode::PARAM));
        } else {
            // case 2: arguments are not functional tensors, so we no-op and redispatch.
            at::AutoDispatchSkipFunctionalize guard;
            at_npu::native::custom_ops::npu_scatter_pa_kv_cache(key_, value_, key_cache_, value_cache_, slot_mapping_, compress_lens_, compress_seq_offsets_, seq_lens_);

        }
    } else {
        ::std::tuple<at::Tensor,at::Tensor> tmp_output;
        {
            at::AutoDispatchSkipFunctionalize guard;
            tmp_output = at_npu::native::custom_ops::npu_scatter_pa_kv_cache_functional(key_, value_, key_cache_, value_cache_, slot_mapping_, compress_lens_, compress_seq_offsets_, seq_lens_);
        }
        at::functionalization::impl::replace_(key_cache, std::get<0>(tmp_output));
        at::functionalization::impl::commit_update(key_cache);
        at::functionalization::impl::sync(key_cache);
at::functionalization::impl::replace_(value_cache, std::get<1>(tmp_output));
        at::functionalization::impl::commit_update(value_cache);
        at::functionalization::impl::sync(value_cache);

    }
}

at::Tensor & npu_silu_(c10::DispatchKeySet dispatchKeySet, at::Tensor & self) {
    if (true) {
        // Before converting the mutable op to its functional variant, run meta tensors through the original op.
        // This will help us catch shape errors that apply to inplace ops that wouldn't apply to their functional variants.
        // (We can only do this for inplace ops today though, because they technicaly all support meta tensors).
        auto self_meta = to_meta(self);
        at::AutoDispatchSkipFunctionalize func_guard;
        c10::impl::ExcludeDispatchKeyGuard guard(exclude_keys_for_meta_dispatch);
        at_npu::native::custom_ops::npu_silu_(self_meta);
    }

      at::Tensor self_;
      if (at::functionalization::impl::isFunctionalTensor(self)) {
        at::functionalization::impl::sync(self);
        self_ = at::functionalization::impl::from_functional_tensor(self);
      } else {
        self_ = self;
      }
    if (!(true && at::functionalization::impl::isFunctionalTensor(self))) {
        if (false) {
            // case 1: trying to mutate a non functional tensor with a functional tensor is an error
            TORCH_INTERNAL_ASSERT(false,
            "mutating a non-functional tensor with a functional tensor is not allowed.",
            " Please ensure that all of your inputs are wrapped inside of a functionalize() call.", PTA_ERROR(ErrCode::PARAM));
        } else {
            // case 2: arguments are not functional tensors, so we no-op and redispatch.
            at::AutoDispatchSkipFunctionalize guard;
            at::Tensor tmp_output = at_npu::native::custom_ops::npu_silu_(self_);
            return self;
        }
    } else {
        at::Tensor tmp_output;
        {
            at::AutoDispatchSkipFunctionalize guard;
            tmp_output = at_npu::native::custom_ops::npu_silu(self_);
        }
        at::functionalization::impl::replace_(self, tmp_output);
        at::functionalization::impl::commit_update(self);
        at::functionalization::impl::sync(self);
        return self;
    }
}

at::Tensor & npu_slice_out_out(c10::DispatchKeySet dispatchKeySet, const at::Tensor & self, at::IntArrayRef offsets, at::IntArrayRef size, at::Tensor & out) {
    if (false) {
        // Before converting the mutable op to its functional variant, run meta tensors through the original op.
        // This will help us catch shape errors that apply to inplace ops that wouldn't apply to their functional variants.
        // (We can only do this for inplace ops today though, because they technicaly all support meta tensors).
        auto self_meta = to_meta(self);
        auto out_meta = to_meta(out);
        at::AutoDispatchSkipFunctionalize func_guard;
        c10::impl::ExcludeDispatchKeyGuard guard(exclude_keys_for_meta_dispatch);
        at_npu::native::custom_ops::npu_slice_out(self_meta, offsets, size, out_meta);
    }

      at::Tensor self_;
      if (at::functionalization::impl::isFunctionalTensor(self)) {
        at::functionalization::impl::sync(self);
        self_ = at::functionalization::impl::from_functional_tensor(self);
      } else {
        self_ = self;
      }

      at::Tensor out_;
      if (at::functionalization::impl::isFunctionalTensor(out)) {
        at::functionalization::impl::sync(out);
        out_ = at::functionalization::impl::from_functional_tensor(out);
      } else {
        out_ = out;
      }
    if (!(true && at::functionalization::impl::isFunctionalTensor(out))) {
        if (false || at::functionalization::impl::isFunctionalTensor(self)) {
            // case 1: trying to mutate a non functional tensor with a functional tensor is an error
            TORCH_INTERNAL_ASSERT(false,
            "mutating a non-functional tensor with a functional tensor is not allowed.",
            " Please ensure that all of your inputs are wrapped inside of a functionalize() call.", PTA_ERROR(ErrCode::PARAM));
        } else {
            // case 2: arguments are not functional tensors, so we no-op and redispatch.
            at::AutoDispatchSkipFunctionalize guard;
            at::Tensor tmp_output = at_npu::native::custom_ops::npu_slice_out(self_, offsets, size, out_);
            return out;
        }
    } else {
        at::Tensor tmp_output;
        {
            at::AutoDispatchSkipFunctionalize guard;
            tmp_output = at_npu::native::custom_ops::npu_slice(self_, offsets, size);
        }
        at::functionalization::impl::replace_(out, tmp_output);
        at::functionalization::impl::commit_update(out);
        at::functionalization::impl::sync(out);
        return out;
    }
}

at::Tensor & npu_sort_v2_out_out(c10::DispatchKeySet dispatchKeySet, const at::Tensor & self, int64_t dim, bool descending, at::Tensor & out) {
    if (false) {
        // Before converting the mutable op to its functional variant, run meta tensors through the original op.
        // This will help us catch shape errors that apply to inplace ops that wouldn't apply to their functional variants.
        // (We can only do this for inplace ops today though, because they technicaly all support meta tensors).
        auto self_meta = to_meta(self);
        auto out_meta = to_meta(out);
        at::AutoDispatchSkipFunctionalize func_guard;
        c10::impl::ExcludeDispatchKeyGuard guard(exclude_keys_for_meta_dispatch);
        at_npu::native::custom_ops::npu_sort_v2_out(self_meta, dim, descending, out_meta);
    }

      at::Tensor self_;
      if (at::functionalization::impl::isFunctionalTensor(self)) {
        at::functionalization::impl::sync(self);
        self_ = at::functionalization::impl::from_functional_tensor(self);
      } else {
        self_ = self;
      }

      at::Tensor out_;
      if (at::functionalization::impl::isFunctionalTensor(out)) {
        at::functionalization::impl::sync(out);
        out_ = at::functionalization::impl::from_functional_tensor(out);
      } else {
        out_ = out;
      }
    if (!(true && at::functionalization::impl::isFunctionalTensor(out))) {
        if (false || at::functionalization::impl::isFunctionalTensor(self)) {
            // case 1: trying to mutate a non functional tensor with a functional tensor is an error
            TORCH_INTERNAL_ASSERT(false,
            "mutating a non-functional tensor with a functional tensor is not allowed.",
            " Please ensure that all of your inputs are wrapped inside of a functionalize() call.", PTA_ERROR(ErrCode::PARAM));
        } else {
            // case 2: arguments are not functional tensors, so we no-op and redispatch.
            at::AutoDispatchSkipFunctionalize guard;
            at::Tensor tmp_output = at_npu::native::custom_ops::npu_sort_v2_out(self_, dim, descending, out_);
            return out;
        }
    } else {
        at::Tensor tmp_output;
        {
            at::AutoDispatchSkipFunctionalize guard;
            tmp_output = at_npu::native::custom_ops::npu_sort_v2(self_, dim, descending);
        }
        at::functionalization::impl::replace_(out, tmp_output);
        at::functionalization::impl::commit_update(out);
        at::functionalization::impl::sync(out);
        return out;
    }
}

at::Tensor & npu_stride_copy_out_out(c10::DispatchKeySet dispatchKeySet, const at::Tensor & self, at::IntArrayRef shape, at::IntArrayRef stride, const at::Scalar & storage_offset, at::Tensor & out) {
    if (false) {
        // Before converting the mutable op to its functional variant, run meta tensors through the original op.
        // This will help us catch shape errors that apply to inplace ops that wouldn't apply to their functional variants.
        // (We can only do this for inplace ops today though, because they technicaly all support meta tensors).
        auto self_meta = to_meta(self);
        auto out_meta = to_meta(out);
        at::AutoDispatchSkipFunctionalize func_guard;
        c10::impl::ExcludeDispatchKeyGuard guard(exclude_keys_for_meta_dispatch);
        at_npu::native::custom_ops::npu_stride_copy_out(self_meta, shape, stride, storage_offset, out_meta);
    }

      at::Tensor self_;
      if (at::functionalization::impl::isFunctionalTensor(self)) {
        at::functionalization::impl::sync(self);
        self_ = at::functionalization::impl::from_functional_tensor(self);
      } else {
        self_ = self;
      }

      at::Tensor out_;
      if (at::functionalization::impl::isFunctionalTensor(out)) {
        at::functionalization::impl::sync(out);
        out_ = at::functionalization::impl::from_functional_tensor(out);
      } else {
        out_ = out;
      }
    if (!(true && at::functionalization::impl::isFunctionalTensor(out))) {
        if (false || at::functionalization::impl::isFunctionalTensor(self)) {
            // case 1: trying to mutate a non functional tensor with a functional tensor is an error
            TORCH_INTERNAL_ASSERT(false,
            "mutating a non-functional tensor with a functional tensor is not allowed.",
            " Please ensure that all of your inputs are wrapped inside of a functionalize() call.", PTA_ERROR(ErrCode::PARAM));
        } else {
            // case 2: arguments are not functional tensors, so we no-op and redispatch.
            at::AutoDispatchSkipFunctionalize guard;
            at::Tensor tmp_output = at_npu::native::custom_ops::npu_stride_copy_out(self_, shape, stride, storage_offset, out_);
            return out;
        }
    } else {
        at::Tensor tmp_output;
        {
            at::AutoDispatchSkipFunctionalize guard;
            tmp_output = at_npu::native::custom_ops::npu_stride_copy(self_, shape, stride, storage_offset);
        }
        at::functionalization::impl::replace_(out, tmp_output);
        at::functionalization::impl::commit_update(out);
        at::functionalization::impl::sync(out);
        return out;
    }
}

at::Tensor & npu_transpose_out_out(c10::DispatchKeySet dispatchKeySet, const at::Tensor & self, at::IntArrayRef perm, bool require_contiguous, at::Tensor & out) {
    if (false) {
        // Before converting the mutable op to its functional variant, run meta tensors through the original op.
        // This will help us catch shape errors that apply to inplace ops that wouldn't apply to their functional variants.
        // (We can only do this for inplace ops today though, because they technicaly all support meta tensors).
        auto self_meta = to_meta(self);
        auto out_meta = to_meta(out);
        at::AutoDispatchSkipFunctionalize func_guard;
        c10::impl::ExcludeDispatchKeyGuard guard(exclude_keys_for_meta_dispatch);
        at_npu::native::custom_ops::npu_transpose_out(self_meta, perm, require_contiguous, out_meta);
    }

      at::Tensor self_;
      if (at::functionalization::impl::isFunctionalTensor(self)) {
        at::functionalization::impl::sync(self);
        self_ = at::functionalization::impl::from_functional_tensor(self);
      } else {
        self_ = self;
      }

      at::Tensor out_;
      if (at::functionalization::impl::isFunctionalTensor(out)) {
        at::functionalization::impl::sync(out);
        out_ = at::functionalization::impl::from_functional_tensor(out);
      } else {
        out_ = out;
      }
    if (!(true && at::functionalization::impl::isFunctionalTensor(out))) {
        if (false || at::functionalization::impl::isFunctionalTensor(self)) {
            // case 1: trying to mutate a non functional tensor with a functional tensor is an error
            TORCH_INTERNAL_ASSERT(false,
            "mutating a non-functional tensor with a functional tensor is not allowed.",
            " Please ensure that all of your inputs are wrapped inside of a functionalize() call.", PTA_ERROR(ErrCode::PARAM));
        } else {
            // case 2: arguments are not functional tensors, so we no-op and redispatch.
            at::AutoDispatchSkipFunctionalize guard;
            at::Tensor tmp_output = at_npu::native::custom_ops::npu_transpose_out(self_, perm, require_contiguous, out_);
            return out;
        }
    } else {
        at::Tensor tmp_output;
        {
            at::AutoDispatchSkipFunctionalize guard;
            tmp_output = at_npu::native::custom_ops::npu_transpose(self_, perm, require_contiguous);
        }
        at::functionalization::impl::replace_(out, tmp_output);
        at::functionalization::impl::commit_update(out);
        at::functionalization::impl::sync(out);
        return out;
    }
}

at::Tensor & scatter_update_(c10::DispatchKeySet dispatchKeySet, at::Tensor & self, const at::Tensor & indices, const at::Tensor & updates, int64_t axis) {
    if (true) {
        // Before converting the mutable op to its functional variant, run meta tensors through the original op.
        // This will help us catch shape errors that apply to inplace ops that wouldn't apply to their functional variants.
        // (We can only do this for inplace ops today though, because they technicaly all support meta tensors).
        auto self_meta = to_meta(self);
        auto indices_meta = to_meta(indices);
        auto updates_meta = to_meta(updates);
        at::AutoDispatchSkipFunctionalize func_guard;
        c10::impl::ExcludeDispatchKeyGuard guard(exclude_keys_for_meta_dispatch);
        at_npu::native::custom_ops::scatter_update_(self_meta, indices_meta, updates_meta, axis);
    }

      at::Tensor self_;
      if (at::functionalization::impl::isFunctionalTensor(self)) {
        at::functionalization::impl::sync(self);
        self_ = at::functionalization::impl::from_functional_tensor(self);
      } else {
        self_ = self;
      }

      at::Tensor indices_;
      if (at::functionalization::impl::isFunctionalTensor(indices)) {
        at::functionalization::impl::sync(indices);
        indices_ = at::functionalization::impl::from_functional_tensor(indices);
      } else {
        indices_ = indices;
      }

      at::Tensor updates_;
      if (at::functionalization::impl::isFunctionalTensor(updates)) {
        at::functionalization::impl::sync(updates);
        updates_ = at::functionalization::impl::from_functional_tensor(updates);
      } else {
        updates_ = updates;
      }
    if (!(true && at::functionalization::impl::isFunctionalTensor(self))) {
        if (false || at::functionalization::impl::isFunctionalTensor(indices) || at::functionalization::impl::isFunctionalTensor(updates)) {
            // case 1: trying to mutate a non functional tensor with a functional tensor is an error
            TORCH_INTERNAL_ASSERT(false,
            "mutating a non-functional tensor with a functional tensor is not allowed.",
            " Please ensure that all of your inputs are wrapped inside of a functionalize() call.", PTA_ERROR(ErrCode::PARAM));
        } else {
            // case 2: arguments are not functional tensors, so we no-op and redispatch.
            at::AutoDispatchSkipFunctionalize guard;
            at::Tensor tmp_output = at_npu::native::custom_ops::scatter_update_(self_, indices_, updates_, axis);
            return self;
        }
    } else {
        at::Tensor tmp_output;
        {
            at::AutoDispatchSkipFunctionalize guard;
            tmp_output = at_npu::native::custom_ops::scatter_update(self_, indices_, updates_, axis);
        }
        at::functionalization::impl::replace_(self, tmp_output);
        at::functionalization::impl::commit_update(self);
        at::functionalization::impl::sync(self);
        return self;
    }
}

at::Tensor & _npu_index_add_(c10::DispatchKeySet dispatchKeySet, at::Tensor & self, const at::Tensor & index, const at::Tensor & source, const at::Scalar & alpha) {
    if (true) {
        // Before converting the mutable op to its functional variant, run meta tensors through the original op.
        // This will help us catch shape errors that apply to inplace ops that wouldn't apply to their functional variants.
        // (We can only do this for inplace ops today though, because they technicaly all support meta tensors).
        auto self_meta = to_meta(self);
        auto index_meta = to_meta(index);
        auto source_meta = to_meta(source);
        at::AutoDispatchSkipFunctionalize func_guard;
        c10::impl::ExcludeDispatchKeyGuard guard(exclude_keys_for_meta_dispatch);
        at_npu::native::custom_ops::_npu_index_add_(self_meta, index_meta, source_meta, alpha);
    }

      at::Tensor self_;
      if (at::functionalization::impl::isFunctionalTensor(self)) {
        at::functionalization::impl::sync(self);
        self_ = at::functionalization::impl::from_functional_tensor(self);
      } else {
        self_ = self;
      }

      at::Tensor index_;
      if (at::functionalization::impl::isFunctionalTensor(index)) {
        at::functionalization::impl::sync(index);
        index_ = at::functionalization::impl::from_functional_tensor(index);
      } else {
        index_ = index;
      }

      at::Tensor source_;
      if (at::functionalization::impl::isFunctionalTensor(source)) {
        at::functionalization::impl::sync(source);
        source_ = at::functionalization::impl::from_functional_tensor(source);
      } else {
        source_ = source;
      }
    if (!(true && at::functionalization::impl::isFunctionalTensor(self))) {
        if (false || at::functionalization::impl::isFunctionalTensor(index) || at::functionalization::impl::isFunctionalTensor(source)) {
            // case 1: trying to mutate a non functional tensor with a functional tensor is an error
            TORCH_INTERNAL_ASSERT(false,
            "mutating a non-functional tensor with a functional tensor is not allowed.",
            " Please ensure that all of your inputs are wrapped inside of a functionalize() call.", PTA_ERROR(ErrCode::PARAM));
        } else {
            // case 2: arguments are not functional tensors, so we no-op and redispatch.
            at::AutoDispatchSkipFunctionalize guard;
            at::Tensor tmp_output = at_npu::native::custom_ops::_npu_index_add_(self_, index_, source_, alpha);
            return self;
        }
    } else {
        at::Tensor tmp_output;
        {
            at::AutoDispatchSkipFunctionalize guard;
            tmp_output = at_npu::native::custom_ops::_npu_index_add(self_, index_, source_, alpha);
        }
        at::functionalization::impl::replace_(self, tmp_output);
        at::functionalization::impl::commit_update(self);
        at::functionalization::impl::sync(self);
        return self;
    }
}

}  // namespace functionalization

namespace {

TORCH_LIBRARY_IMPL(npu, Functionalize, m) {
    m.impl("npu_format_cast_.acl_format", TORCH_FN(functionalization::npu_format_cast__acl_format));
    m.impl("npu_kv_rmsnorm_rope_cache_v2", TORCH_FN(functionalization::npu_kv_rmsnorm_rope_cache_v2));
    m.impl("npu_batch_gather_matmul_", TORCH_FN(functionalization::npu_batch_gather_matmul_));
    m.impl("npu_broadcast.out", TORCH_FN(functionalization::npu_broadcast_out_out));
    m.impl("npu_conv2d.out", TORCH_FN(functionalization::npu_conv2d_out_out));
    m.impl("npu_conv3d.out", TORCH_FN(functionalization::npu_conv3d_out_out));
    m.impl("npu_indexing.out", TORCH_FN(functionalization::npu_indexing_out_out));
    m.impl("npu_quant_scatter_", TORCH_FN(functionalization::npu_quant_scatter_));
    m.impl("npu_reshape.out", TORCH_FN(functionalization::npu_reshape_out_out));
    m.impl("npu_scatter_list_", TORCH_FN(functionalization::npu_scatter_list_));
    m.impl("npu_scatter_nd_update_", TORCH_FN(functionalization::npu_scatter_nd_update_));
    m.impl("npu_scatter_pa_kv_cache", TORCH_FN(functionalization::npu_scatter_pa_kv_cache));
    m.impl("npu_silu_", TORCH_FN(functionalization::npu_silu_));
    m.impl("npu_slice.out", TORCH_FN(functionalization::npu_slice_out_out));
    m.impl("npu_sort_v2.out", TORCH_FN(functionalization::npu_sort_v2_out_out));
    m.impl("npu_stride_copy.out", TORCH_FN(functionalization::npu_stride_copy_out_out));
    m.impl("npu_transpose.out", TORCH_FN(functionalization::npu_transpose_out_out));
    m.impl("scatter_update_", TORCH_FN(functionalization::scatter_update_));
    m.impl("_npu_index_add_", TORCH_FN(functionalization::_npu_index_add_));;
}

}  // namespace

} // namespace at_npu
